version: '3.4'

services:
  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  frontend:
    build:
      context: .
      dockerfile: src/Frontend/Dockerfile
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  authservice:
      image: ${DOCKER_REGISTRY-}authservice
      build:
          context: .
          dockerfile: src/AuthService/Dockerfile
      ports:
        - "7001:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=auth-db;Port=5432;Database=aethera_auth;Username=aethera;Password=a123123a
      depends_on:
        - auth-db
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M

  auth-db:
    image: postgres:15
    container_name: aethera-auth-db
    environment:
      POSTGRES_DB: aethera_auth
      POSTGRES_USER: aethera
      POSTGRES_PASSWORD: a123123a
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 512M
          reservations:
            cpus: '0.25'
            memory: 256M

volumes:
  auth-db-data: