version: '3.4'

services:
  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  frontend:
    build:
      context: .
      dockerfile: src/Frontend/Dockerfile
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  helloservice:
    image: ${DOCKER_REGISTRY-}helloservice
    build:
      context: .
      dockerfile: src/HelloService/Dockerfile
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
